"""Baseline schema.

Creates the extensions, every table Phase 0 needs, and the tier columns.
Correspondents, assets, known forms, classifications and embeddings arrive in
Phases 3 and 5 — adding a nullable column later is cheap, but retrofitting the
tier and library columns onto already-filed documents would mean re-touching
every one of them, so those are here from the start (REQ-089, REQ-099).

Deliberately hand-written rather than autogenerated, so the baseline is a
reviewed artifact.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-27
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUMS: dict[str, tuple[str, ...]] = {
    "library_kind": ("personal", "shared"),
    "membership_role": ("owner", "contributor", "reader"),
    "ingest_source": ("web_upload", "watched_folder", "camera", "bulk_import"),
    "source_file_state": (
        "received",
        "duplicate",
        "normalizing",
        "paging",
        "segmenting",
        "processed",
        "failed",
    ),
    "sensitivity": ("normal", "sensitive", "vital"),
    "redundancy": ("local", "local_plus_offsite"),
    "review_state": ("filed", "needs_review", "pending_classification", "failed"),
    "tag_source": ("ai", "rule", "human"),
    "job_stage": (
        "ingest",
        "normalize",
        "page",
        "segment",
        "embed",
        "classify",
        "rules",
        "file",
        "mirror",
    ),
    "job_state": ("queued", "running", "succeeded", "failed", "dead_letter"),
    "actor_type": ("human", "ai", "rule", "system"),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type; never emit CREATE TYPE inline."""
    return postgresql.ENUM(*ENUMS[name], name=name, create_type=False)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    bind = op.get_bind()
    for name, values in ENUMS.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    uuid_pk = sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True)
    now = sa.text("now()")

    # ---- access boundary -------------------------------------------------
    op.create_table(
        "library",
        uuid_pk,
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", _enum("library_kind"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
    )

    op.create_table(
        "app_user",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.UniqueConstraint("email", name="uq_app_user_email"),
    )

    op.create_table(
        "refresh_token",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True)),
        sa.Column("replaced_by_id", postgresql.UUID(as_uuid=True)),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name="fk_refresh_token_user_id_app_user"
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_token.id"],
            name="fk_refresh_token_replaced_by_id_refresh_token",
        ),
        sa.UniqueConstraint("token_hash", name="uq_refresh_token_token_hash"),
    )
    op.create_index("ix_refresh_token_user_id", "refresh_token", ["user_id"])

    op.create_table(
        "membership",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("library_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", _enum("membership_role"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name="fk_membership_user_id_app_user"
        ),
        sa.ForeignKeyConstraint(
            ["library_id"], ["library.id"], name="fk_membership_library_id_library"
        ),
        sa.UniqueConstraint("user_id", "library_id", name="uq_membership_user_id_library_id"),
    )
    op.create_index("ix_membership_user_id", "membership", ["user_id"])
    op.create_index("ix_membership_library_id", "membership", ["library_id"])

    # ---- immutable originals --------------------------------------------
    op.create_table(
        "source_file",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("library_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.Text()),
        sa.Column("original_filename", sa.Text()),
        sa.Column("ingest_source", _enum("ingest_source"), nullable=False),
        sa.Column(
            "ingest_metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("page_count", sa.Integer()),
        sa.Column(
            "state", _enum("source_file_state"), nullable=False, server_default="received"
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.ForeignKeyConstraint(
            ["library_id"], ["library.id"], name="fk_source_file_library_id_library"
        ),
        # Content address. Exact deduplication is free.
        sa.UniqueConstraint("sha256", name="uq_source_file_sha256"),
    )
    op.create_index("ix_source_file_library_id", "source_file", ["library_id"])
    op.create_index("ix_source_file_state", "source_file", ["state"])

    # ---- the unit of search ---------------------------------------------
    op.create_table(
        "page",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text()),
        # Generated, so it can never drift out of sync with `text`.
        sa.Column(
            "text_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(text, ''))", persisted=True),
        ),
        sa.Column("word_boxes_path", sa.Text()),
        sa.Column("render_path", sa.Text()),
        sa.Column("thumb_path", sa.Text()),
        sa.ForeignKeyConstraint(
            ["source_file_id"], ["source_file.id"], name="fk_page_source_file_id_source_file"
        ),
        sa.UniqueConstraint(
            "source_file_id", "page_number", name="uq_page_source_file_id_page_number"
        ),
    )
    op.create_index("ix_page_source_file_id", "page", ["source_file_id"])
    # The primary search index. Page-granular, which is the whole product bet.
    op.create_index(
        "ix_page_text_tsv", "page", ["text_tsv"], postgresql_using="gin"
    )

    # ---- the logical unit ------------------------------------------------
    op.create_table(
        "document",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("library_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text()),
        sa.Column("summary", sa.Text()),
        sa.Column("document_date", sa.Date()),
        sa.Column("sensitivity", _enum("sensitivity"), nullable=False, server_default="normal"),
        sa.Column("redundancy", _enum("redundancy"), nullable=False, server_default="local"),
        sa.Column(
            "review_state",
            _enum("review_state"),
            nullable=False,
            server_default="pending_classification",
        ),
        sa.Column("is_backlog", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.ForeignKeyConstraint(
            ["library_id"], ["library.id"], name="fk_document_library_id_library"
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"], ["source_file.id"], name="fk_document_source_file_id_source_file"
        ),
        sa.CheckConstraint("page_start >= 1", name="ck_document_page_start_positive"),
        sa.CheckConstraint("page_end >= page_start", name="ck_document_page_range_ordered"),
    )
    op.create_index("ix_document_library_id", "document", ["library_id"])
    op.create_index("ix_document_source_file_id", "document", ["source_file_id"])
    op.create_index("ix_document_document_date", "document", ["document_date"])
    op.create_index("ix_document_sensitivity", "document", ["sensitivity"])
    op.create_index("ix_document_review_state", "document", ["review_state"])
    # Typo tolerance — the gap Postgres FTS alone leaves.
    op.create_index(
        "ix_document_title_trgm",
        "document",
        ["title"],
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )

    # ---- taxonomy --------------------------------------------------------
    op.create_table(
        "tag",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        # NULL means the tag is shared across every library.
        sa.Column("library_id", postgresql.UUID(as_uuid=True)),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("color", sa.Text()),
        sa.Column("created_by", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.ForeignKeyConstraint(["library_id"], ["library.id"], name="fk_tag_library_id_library"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name="fk_tag_created_by_app_user"
        ),
    )
    op.create_index("ix_tag_library_id", "tag", ["library_id"])
    op.create_index(
        "ix_tag_name_trgm",
        "tag",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # NULLS NOT DISTINCT (PG15+) so a global tag's slug is still unique.
    op.execute(
        "ALTER TABLE tag ADD CONSTRAINT uq_tag_library_id_slug "
        "UNIQUE NULLS NOT DISTINCT (library_id, slug)"
    )

    op.create_table(
        "document_tag",
        sa.Column("document_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tag_id", postgresql.UUID(as_uuid=True), primary_key=True),
        # Provenance lives on the link row, so the why-panel can tell the model,
        # a rule, and a human apart.
        sa.Column("source", _enum("tag_source"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name="fk_document_tag_document_id_document"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], name="fk_document_tag_tag_id_tag"),
    )

    # ---- operations ------------------------------------------------------
    op.create_table(
        "job",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True)),
        sa.Column("document_id", postgresql.UUID(as_uuid=True)),
        sa.Column("stage", _enum("job_stage"), nullable=False),
        sa.Column("state", _enum("job_state"), nullable=False, server_default="queued"),
        sa.Column("prompt_version", sa.Text()),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text()),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.Column("locked_at", sa.DateTime(timezone=True)),
        sa.Column("locked_by", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
        sa.ForeignKeyConstraint(
            ["source_file_id"], ["source_file.id"], name="fk_job_source_file_id_source_file"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name="fk_job_document_id_document"
        ),
    )
    op.create_index("ix_job_source_file_id", "job", ["source_file_id"])
    op.create_index("ix_job_document_id", "job", ["document_id"])
    # Queue polling.
    op.create_index("ix_job_state_scheduled_for", "job", ["state", "scheduled_for"])
    # Idempotency key. document_id and prompt_version are null for file-scoped
    # stages, so the uniqueness has to treat those nulls as equal.
    op.execute(
        "ALTER TABLE job ADD CONSTRAINT "
        "uq_job_source_file_id_document_id_stage_prompt_version "
        "UNIQUE NULLS NOT DISTINCT (source_file_id, document_id, stage, prompt_version)"
    )

    op.create_table(
        "audit_event",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("actor_type", _enum("actor_type"), nullable=False),
        sa.Column("actor_id", postgresql.UUID(as_uuid=True)),
        sa.Column("rule_id", postgresql.UUID(as_uuid=True)),
        sa.Column("before", postgresql.JSONB()),
        sa.Column("after", postgresql.JSONB()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=now),
    )
    op.create_index("ix_audit_event_entity", "audit_event", ["entity_type", "entity_id"])
    op.create_index("ix_audit_event_created_at", "audit_event", ["created_at"])


def downgrade() -> None:
    # A downgrade drops the archive's schema. It exists so the migration is
    # reversible during rehearsal on the staging stack (REQ-115) and is never
    # run against the real archive.
    for table in (
        "audit_event",
        "job",
        "document_tag",
        "tag",
        "document",
        "page",
        "source_file",
        "membership",
        "refresh_token",
        "app_user",
        "library",
    ):
        op.drop_table(table)

    bind = op.get_bind()
    for name in ENUMS:
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
