#!/usr/bin/env python3
"""Run mypy over `api/` and `worker/`, and refuse to let the number grow.

    make typecheck                     # the gate
    python scripts/typecheck.py --update   # after fixing some

mypy was a declared dev dependency with no configuration, no invocation and no
note saying that was deliberate (CR-089). The annotations were already written —
95% of functions in `api/` and `worker/` carry a return type and there is not one
`# type: ignore` — so the expensive half was paid for and the cheap half was
missing.

**Why a baseline rather than a clean run.** There are errors today. Fixing all of
them touches thirty files across every subsystem, which is a project and not a
review round; turning the gate on with them unfixed makes it red on arrival, and
a gate that is red on arrival is one somebody switches off within a month. So
what is gated is the count per file and per error code: **a file may not gain an
error.** That is the whole rule, and it is one-directional on purpose — a change
that *fixes* a type error must not turn somebody else's build red, because a gate
that punishes an improvement is a gate people learn to route around. Shrinkage is
reported loudly and exits zero; refresh the baseline when you see it, or the
ratchet keeps room for a regression it should have shut out.

The counts are per file and per error code rather than a single total, because a
total lets a new `arg-type` in one module hide behind a fix in another.

**The environment matters.** mypy's answer depends on which packages are
installed: a library that is present and typed is checked, and the same library
absent is `Any`. The baseline is generated in — and the gate runs in — an
environment carrying the base and `dev` dependency groups and not the `worker`
extra, which is what both the `test` compose service and CI's lint job install.
Run it anywhere else and the diff is the environment, not the code.
"""

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BASELINE = Path(__file__).resolve().parent / "mypy-baseline.json"
TARGETS = ["api", "worker"]

# `path:line: error: message  [code]`. Notes and the summary line are ignored;
# only errors are counted.
ERROR = re.compile(r"^(?P<path>[^:]+):\d+:(?:\d+:)? error: .*\[(?P<code>[a-z-]+)\]\s*$")


def run_mypy() -> tuple[int, str]:
    result = subprocess.run(
        [sys.executable, "-m", "mypy", *TARGETS],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout + result.stderr


def tally(output: str) -> dict[str, dict[str, int]]:
    counts: dict[str, Counter] = {}
    for line in output.splitlines():
        match = ERROR.match(line.strip())
        if match is None:
            continue
        counts.setdefault(match["path"], Counter())[match["code"]] += 1
    return {path: dict(sorted(codes.items())) for path, codes in sorted(counts.items())}


def load_baseline() -> dict[str, dict[str, int]]:
    if not BASELINE.exists():
        return {}
    return json.loads(BASELINE.read_text())["files"]


def total(counts: dict[str, dict[str, int]]) -> int:
    return sum(sum(codes.values()) for codes in counts.values())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the baseline from this run; review the diff before committing",
    )
    args = parser.parse_args()

    code, output = run_mypy()
    counts = tally(output)

    # A crash, a bad config or an unparsable report: mypy exited non-zero and we
    # found no errors to explain it. Never silently pass on that — a checker that
    # examines nothing is the badge that is always on.
    if code not in (0, 1) or (code != 0 and not counts):
        print(output)
        print(f"::error::mypy exited {code} without a report this script could read")
        return 2

    if args.update:
        BASELINE.write_text(
            json.dumps(
                {
                    "_": "Generated by scripts/typecheck.py --update. Counts only "
                    "go down; see CLAUDE.md, Conventions.",
                    "total": total(counts),
                    "files": counts,
                },
                indent=2,
            )
            + "\n"
        )
        print(f"baseline rewritten: {total(counts)} error(s) in {len(counts)} file(s)")
        return 0

    baseline = load_baseline()
    grew, shrank = [], []
    for path in sorted(set(baseline) | set(counts)):
        was, now = baseline.get(path, {}), counts.get(path, {})
        for error_code in sorted(set(was) | set(now)):
            before, after = was.get(error_code, 0), now.get(error_code, 0)
            if after > before:
                grew.append(f"  {path}  [{error_code}]  {before} -> {after}")
            elif after < before:
                shrank.append(f"  {path}  [{error_code}]  {before} -> {after}")

    if grew:
        print(output)
        print("mypy found errors this code did not have before:")
        print("\n".join(grew))
        print(
            "\nFix them. If the type is genuinely unknowable here, say so in a "
            "comment beside it rather than widening the annotation."
        )
        return 1

    if shrank:
        # Not a failure. See the module docstring: an improvement must not go red.
        print("mypy is happier than the baseline says:")
        print("\n".join(shrank))
        print(
            "\nTighten the ratchet — a baseline looser than reality keeps room "
            "for a regression it should have shut out:\n"
            "  python scripts/typecheck.py --update"
        )

    print(f"typecheck: {total(counts)} known error(s), none new")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
